### ISSUE TITLE
Bug,虽然不是必现,但是出现机率也很大

### ISSUE THREAD

**Issue by 743306400** [xfhomedream/color_pick#1]
在底色圆盘上手指触点和选择颜色的小圆,不在同一个点上,大佬能修复一下吗?
![QQ截图20201105102609](https://user-images.githubusercontent.com/20965040/98190161-66a78a00-1f51-11eb-8421-78794df35e34.png)

**Comment by xfmaster** [comment]
好的，感谢反馈，最近抽时间修改下

**Comment by xfmaster** [comment]
> 在底色圆盘上手指触点和选择颜色的小圆,不在同一个点上,大佬能修复一下吗?
> ![QQ截图20201105102609](https://user-images.githubusercontent.com/20965040/98190161-66a78a00-1f51-11eb-8421-78794df35e34.png)

请问是怎么操作出现的这个问题了，我这试了没有复现这个问题

**Comment by 743306400** [comment]
> > 在底色圆盘上手指触点和选择颜色的小圆,不在同一个点上,大佬能修复一下吗?
> > ![QQ截图20201105102609](https://user-images.githubusercontent.com/20965040/98190161-66a78a00-1f51-11eb-8421-78794df35e34.png)
> 
> 请问是怎么操作出现的这个问题了，我这试了没有复现这个问题

我刚才测了几十次也没复现的了,我也不太清楚怎么去复现,之前只偶尔会遇到,因为最近没怎么搞那个项目

**Comment by xfmaster** [comment]
> > > 在底色圆盘上手指触点和选择颜色的小圆,不在同一个点上,大佬能修复一下吗?
> > > ![QQ截图20201105102609](https://user-images.githubusercontent.com/20965040/98190161-66a78a00-1f51-11eb-8421-78794df35e34.png)
> > 
> > 
> > 请问是怎么操作出现的这个问题了，我这试了没有复现这个问题
> 
> 我刚才测了几十次也没复现的了,我也不太清楚怎么去复现,之前只偶尔会遇到,因为最近没怎么搞那个项目

好的，感谢

**Comment by 743306400** [comment]
![image](https://user-images.githubusercontent.com/20965040/111250771-dc7ed900-8648-11eb-8f8f-4cf65daf8479.png)
我把这里注释了,就正常了,具体原因没有去深究,我怀疑是缓存的边距问题

**Comment by xfmaster** [comment]
> ![image](https://user-images.githubusercontent.com/20965040/111250771-dc7ed900-8648-11eb-8f8f-4cf65daf8479.png)
> 我把这里注释了,就正常了,具体原因没有去深究,我怀疑是缓存的边距问题

OK，感谢，晚点我再看看。
